name: Build and push Nextjs project

on:
  push:
    branches: [scp-tar]

jobs:
  build-and-scp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.jsf
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Tar .next directory
        run: tar -cvf rebuild.tar .next/

      - name: Copy the .next tarball to the remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_SERVER_IP }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          key: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          source: "rebuild.tar"
          target: "/var/www"