name: Docker Image CI

on:
  push:
    branches: [ main ]

env:
  REGISTRY: registry.hub.docker.com
  IMAGE_NAME: ttaccp/actions-test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3.4.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha
          
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Output build tags
      run: echo "Build tags: ${{ steps.meta.outputs.tags }}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}

  # deploy-to-k8s:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Deploy to Kubernetes
  #     uses: azure/k8s-deploy@v1.4
  #     with:
  #       kubeconfig: ${{ secrets.KUBECONFIG }}
  #       images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
  #       namespace: default
  #       manifests: ./k8s-deployment.yml