name: Build and push Nextjs project

on:
  push:
    branches: [scp-tar]

env:
  TAR_NAME: rebuild.tar
  REMOTE_SERVER_WWW_DIR: /var/tmp
  PM2_SERVER_NAME: all

jobs:
  build-and-scp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Tar .next directory
        run: tar -cvf ${{ env.TAR_NAME }} .next/

      - name: Copy the .next tarball to the remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HG_REMOTE_SERVER_IP }}
          username: ${{ secrets.HG_REMOTE_SERVER_USERNAME }}
          key: ${{ secrets.HG_REMOTE_SERVER_PASSWORD }}
          source: "${{ env.TAR_NAME }}"
          target: "${{ env.REMOTE_SERVER_WWW_DIR }}"

      - name: Unarchive the tarball on the remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HG_REMOTE_SERVER_IP }}
          username: ${{ secrets.HG_REMOTE_SERVER_USERNAME }}
          key: ${{ secrets.HG_REMOTE_SERVER_PASSWORD }}
          script: |
            scp ${{ env.REMOTE_SERVER_WWW_DIR }}/${{ env.TAR_NAME }} user00@172.27.37.41:${{ env.REMOTE_SERVER_WWW_DIR }}
            ssh user00@172.27.37.41
            cd ${{ env.REMOTE_SERVER_WWW_DIR }}
            tar -xvf ${{ env.TAR_NAME }}
            pm2 reload ${{ env.PM2_SERVER_NAME }}
